# Generated by Django 4.1 on 2023-02-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMER_ID', models.CharField(max_length=20)),
                ('CUSTOMER_PW', models.CharField(max_length=40)),
                ('CUSTOMER_NAME', models.CharField(max_length=40)),
                ('CUSTOMER_BIRTH', models.CharField(max_length=8)),
                ('CUSTOMER_PHONE', models.CharField(max_length=15)),
                ('CUSTOMER_EMAIL', models.EmailField(max_length=254)),
                ('CUSTOMER_ZIPCODE', models.CharField(default='', max_length=10)),
                ('CUSTOMER_ADDR', models.CharField(max_length=300)),
                ('FIRST_VISIT', models.DateTimeField(auto_now_add=True)),
                ('LAST_VISIT', models.DateTimeField()),
                ('VISIT_CNT', models.IntegerField(default=0)),
                ('CUSTOMER_SEX', models.IntegerField(default=0)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY_NAME', models.CharField(max_length=512)),
                ('COMPANY_PHONE', models.CharField(max_length=100)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(max_length=512)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=200)),
                ('BARCODE', models.CharField(default='', max_length=100)),
                ('PRICE', models.IntegerField(default=0)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE_PATH', models.ImageField(blank=True, upload_to='images/')),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=20)),
                ('ORDER', models.IntegerField(default=0)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDER_DATE', models.CharField(default='', max_length=100)),
                ('TOTAL_AMOUNT', models.IntegerField(default=0)),
                ('MEMO', models.CharField(default='', max_length=1024)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
                ('CANCEL_DATE', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('CUSTOMER_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GOODS_NAME', models.CharField(max_length=200)),
                ('GOODS_COUNT', models.IntegerField(default=0)),
                ('PRICE', models.IntegerField(default=0)),
                ('TOTAL_AMOUNT', models.IntegerField(default=0)),
                ('DISCARD', models.BooleanField(default=False)),
                ('GOODS_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.goods')),
                ('ORDER_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.order')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='IMAGE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.goodsimage'),
        ),
        migrations.AddField(
            model_name='goods',
            name='TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.goodstype'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DELIVERY_DATE', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ARRIVAL_DATE', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('DELIVERY_NAME', models.CharField(max_length=200)),
                ('DELIVERY_ADDR', models.CharField(max_length=1024)),
                ('DELIVERY_PHONE', models.CharField(max_length=100)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
                ('CUSTOMER_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.customer')),
                ('DELIVERY_COMPANY', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.deliverycompany')),
                ('DELIVERY_STATUS', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.deliverystatus')),
                ('ORDER_NO', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.order')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='CUSTOMER_RATING',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.rating'),
        ),
    ]
