# Generated by Django 4.1.2 on 2022-11-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='VISIT_CNT',
            field=models.IntegerField(default=0),
        ),
    ]
