# Generated by Django 4.1.2 on 2022-11-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_visit_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=20)),
                ('ORDER', models.IntegerField(default=0)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
    ]
