# Generated by Django 4.1 on 2022-12-09 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer_customer_sex_customer_customer_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=200)),
                ('BARCODE', models.CharField(default='', max_length=100)),
                ('PRICE', models.IntegerField(default=0)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
                ('TYPE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.goodstype')),
            ],
        ),
    ]
