# Generated by Django 4.1.3 on 2023-01-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_goodstype_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY_NAME', models.CharField(max_length=512)),
                ('COMPANY_PHONE', models.CharField(max_length=100)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(max_length=512)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GOODS_NAME', models.CharField(max_length=200)),
                ('GOODS_COUNT', models.IntegerField(default=0)),
                ('PRICE', models.IntegerField(default=0)),
                ('TOTAL_AMOUNT', models.IntegerField(default=0)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
                ('CUSTOMER_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.customer')),
                ('GOODS_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DELIVERY_NAME', models.CharField(max_length=200)),
                ('DELIVERY_ADDR', models.CharField(max_length=1024)),
                ('DELIVERY_PHONE', models.CharField(max_length=100)),
                ('CRTIME', models.DateTimeField(auto_now=True)),
                ('DISCARD', models.BooleanField(default=False)),
                ('CUSTOMER_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.customer')),
                ('DELIVERY_COMPANY', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.deliverycompany')),
                ('DELIVERY_STATUS', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.deliverystatus')),
                ('ORDER_NO', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.delivery')),
            ],
        ),
    ]
