# Generated by Django 4.1 on 2023-01-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_deliverycompany_deliverystatus_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='ARRIVAL_DATE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='DELIVERY_DATE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ORDER_DATE',
            field=models.CharField(default='', max_length=100),
        ),
    ]
