# Generated by Django 4.1 on 2023-01-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delivery_arrival_date_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='GOODS_COUNT',
        ),
        migrations.RemoveField(
            model_name='order',
            name='GOODS_NAME',
        ),
        migrations.RemoveField(
            model_name='order',
            name='GOODS_NO',
        ),
        migrations.RemoveField(
            model_name='order',
            name='PRICE',
        ),
        migrations.AddField(
            model_name='order',
            name='MEMO',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GOODS_NAME', models.CharField(max_length=200)),
                ('GOODS_COUNT', models.IntegerField(default=0)),
                ('PRICE', models.IntegerField(default=0)),
                ('TOTAL_AMOUNT', models.IntegerField(default=0)),
                ('GOODS_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.goods')),
                ('ORDER_NO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.order')),
            ],
        ),
    ]
