# Generated by Django 4.1 on 2023-01-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_order_goods_count_remove_order_goods_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='ORDER_NO',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.order'),
        ),
    ]
