# Generated by Django 4.1 on 2023-01-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_delivery_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='DISCARD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='CANCEL_DATE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='ARRIVAL_DATE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DELIVERY_COMPANY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.deliverycompany'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DELIVERY_DATE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DELIVERY_STATUS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.deliverystatus'),
        ),
    ]
