# Generated by Django 4.1 on 2023-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_item_discard_order_cancel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='CANCEL_DATE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
