# Generated by Django 4.1 on 2023-01-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_cancel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='DELIVERY_COMPANY',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.deliverycompany'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DELIVERY_STATUS',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.deliverystatus'),
        ),
    ]
