# Generated by Django 4.1.2 on 2022-10-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_crtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USER_PW',
            field=models.CharField(default='', max_length=200),
        ),
    ]
